from __future__ import annotations

from typing import Protocol

from .contracts import (
    AgentDescriptor,
    AgentEvent,
    AgentRun,
    Checkpoint,
    DomainEvent,
    MemoryFact,
)


class Stores(Protocol):
    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    async def save_agent(self, agent: AgentDescriptor) -> None: ...

    async def get_agent(self, tenant_id: str, agent_id: str) -> AgentDescriptor | None: ...

    async def save_run(self, run: AgentRun) -> None: ...

    async def get_run(self, tenant_id: str, run_id: str) -> AgentRun | None: ...

    async def append_agent_event(self, event: AgentEvent) -> None: ...

    async def list_agent_events(self, tenant_id: str, run_id: str) -> list[AgentEvent]: ...

    async def save_checkpoint(self, checkpoint: Checkpoint) -> None: ...

    async def save_fact(self, fact: MemoryFact) -> None: ...

    async def get_fact(self, tenant_id: str, fact_id: str) -> MemoryFact | None: ...

    async def list_facts(self, tenant_id: str) -> list[MemoryFact]: ...

    async def append_domain_event(self, event: DomainEvent) -> None: ...


class IdGenerator(Protocol):
    def new(self, prefix: str) -> str: ...
